# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.3.4
      
    - name: Build The Mod
      run: msbuild SlugpupMod.sln /p:Configuration=Release
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: slugpup_mod
        path: bin\Release\*
